In [1]:
import pandas as pd
import numpy as np

## hourly

In [88]:
hr = pd.read_csv('hourly_future_forecast.csv')

In [70]:
hr.columns

Index(['date', 'hour', 'department', 'demand'], dtype='object')

In [42]:
hr.head()

                  date  hour     QueuedTo  predicted_demand
0  2026-08-19 01:00:00     1    ADMISSION          0.261545
1  2026-08-19 01:00:00     1  ANAESTHESIA          0.000489
2  2026-08-19 01:00:00     1    Audiology          0.006173
3  2026-08-19 01:00:00     1   CARDIOLOGY          0.000489
4  2026-08-19 01:00:00     1     CASUALTY          0.029474

In [43]:
hr = hr.rename(columns={
    "predicted_demand": "demand", 
    "QueuedTo": "department"
})

In [44]:
hr.head()

                  date  hour   department    demand
0  2026-08-19 01:00:00     1    ADMISSION  0.261545
1  2026-08-19 01:00:00     1  ANAESTHESIA  0.000489
2  2026-08-19 01:00:00     1    Audiology  0.006173
3  2026-08-19 01:00:00     1   CARDIOLOGY  0.000489
4  2026-08-19 01:00:00     1     CASUALTY  0.029474

In [78]:
hr.to_csv("hourly_future_forecast.csv", index=False)

In [79]:
hrs = pd.read_csv('hourly_capacity_simulation.csv')

In [80]:
hrs.columns

Index(['date', 'hour', 'department', 'service', 'is_24_7', 'operating',
       'forecast_demand', 'simulated_arrivals', 'patients_served',
       'patients_remaining', 'maximum_queue', 'average_wait_minutes',
       'capacity', 'utilization_pct', 'congestion_status'],
      dtype='object')

In [81]:
hrs = hrs.rename(columns={
    "forecast_demand": "demand", 
})

In [82]:
hrs.head()

,date,hour,department,service,is_24_7,operating,demand,simulated_arrivals,patients_served,patients_remaining,maximum_queue,average_wait_minutes,capacity,utilization_pct,congestion_status
0,2026-08-19 01:00:00,1,ADMISSION,Admission Processing,True,True,0.261545,0,0,0,0,0.0,24.0,0.0,Low
1,2026-08-19 01:00:00,1,ANAESTHESIA,Anaesthesia Service,False,False,0.000489,0,0,0,0,0.0,0.0,0.0,Low
2,2026-08-19 01:00:00,1,Audiology,Audiology Assessment,False,False,0.006173,0,0,0,0,0.0,0.0,0.0,Low
3,2026-08-19 01:00:00,1,CARDIOLOGY,Cardiology Consultation,False,False,0.000489,0,0,0,0,0.0,0.0,0.0,Low
4,2026-08-19 01:00:00,1,CASUALTY,Emergency Consultation,True,True,0.029474,0,0,0,0,0.0,18.0,0.0,Low

## daily

In [97]:
dy = pd.read_csv('daily_7day_forecast.csv')

In [98]:
dy.columns

Index(['date', 'QueuedTo', 'prediction'], dtype='object')

In [99]:
dy = dy.rename(columns={
    "prediction": "demand", 
    "QueuedTo": "department"
})

In [100]:
dy.head()

         date   department     demand
0  2026-08-20    ADMISSION  50.315600
1  2026-08-20  ANAESTHESIA   0.910797
2  2026-08-20    Audiology   1.333275
3  2026-08-20   CARDIOLOGY   0.264110
4  2026-08-20     CASUALTY   4.029339

In [101]:
dy.to_csv("daily_7day_forecast.csv", index=False)

## weekly

In [56]:
wk = pd.read_csv('future_weekly_ensemble.csv')

In [69]:
wk.columns

Index(['week', 'department', 'demand'], dtype='object')

In [58]:
wk = wk.rename(columns={
    "ensemble_prediction": "demand", 
    "QueuedTo": "department"
})

In [59]:
wk.head()

,week,department,lgbm_prediction,prophet_prediction,demand
0,2026-08-18,ADMISSION,244.816941,290.856885,267.836913
1,2026-08-18,Audiology,12.629543,12.173273,12.401408
2,2026-08-18,CARDIOLOGY,1.419497,0.654399,1.036948
3,2026-08-18,CASUALTY,43.379603,33.310208,38.344906
4,2026-08-18,CHRONIC CARE CLINIC (DM/HTN/TB/CCC),235.617350,233.616779,234.617064

In [60]:
wk = wk.drop(columns=["lgbm_prediction", "prophet_prediction"])

In [61]:
wk.head()

         week                           department      demand
0  2026-08-18                            ADMISSION  267.836913
1  2026-08-18                            Audiology   12.401408
2  2026-08-18                           CARDIOLOGY    1.036948
3  2026-08-18                             CASUALTY   38.344906
4  2026-08-18  CHRONIC CARE CLINIC (DM/HTN/TB/CCC)  234.617064

In [76]:
wk.to_csv("future_weekly_ensemble.csv", index=False)

In [ ]:
# normalize simulation

In [28]:
hrs = pd.read_csv('hourly_capacity_simulation.csv')

In [71]:
hrs.columns

Index(['date', 'hour', 'department', 'service', 'is_24_7', 'operating',
       'demand', 'simulated_arrivals', 'patients_served', 'patients_remaining',
       'maximum_queue', 'average_wait_minutes', 'capacity', 'utilization_pct',
       'congestion_status'],
      dtype='object')

In [62]:
hrs = hrs.rename(columns={
    "forecast_demand": "demand", 
})

In [63]:
hrs.head()

,date,hour,department,service,is_24_7,operating,demand,simulated_arrivals,patients_served,patients_remaining,maximum_queue,average_wait_minutes,capacity,utilization_pct,congestion_status
0,2026-08-19 01:00:00,1,ADMISSION,Admission Processing,True,True,0.261545,0,0,0,0,0.0,24.0,0.0,Low
1,2026-08-19 01:00:00,1,ANAESTHESIA,Anaesthesia Service,False,False,0.000489,0,0,0,0,0.0,0.0,0.0,Low
2,2026-08-19 01:00:00,1,Audiology,Audiology Assessment,False,False,0.006173,0,0,0,0,0.0,0.0,0.0,Low
3,2026-08-19 01:00:00,1,CARDIOLOGY,Cardiology Consultation,False,False,0.000489,0,0,0,0,0.0,0.0,0.0,Low
4,2026-08-19 01:00:00,1,CASUALTY,Emergency Consultation,True,True,0.029474,0,0,0,0,0.0,18.0,0.0,Low

In [13]:
dys = pd.read_csv('daily_capacity_simulation.csv')

In [72]:
dys.columns

Index(['date', 'department', 'service', 'demand', 'patients_arrivals',
       'patients_served', 'patients_remaining', 'daily_capacity',
       'capacity_utilization_pct', 'congestion_status'],
      dtype='object')

In [64]:
dys = dys.rename(columns={
    "demand_forecast": "demand", 
})

In [65]:
dys.head()

,date,department,service,demand,patients_arrivals,patients_served,patients_remaining,daily_capacity,capacity_utilization_pct,congestion_status
0,2026-08-20,ADMISSION,Admission Processing,50.315600,51,51,0,576.0,8.735347,Low
1,2026-08-20,ANAESTHESIA,Anaesthesia Service,0.910797,1,1,0,96.0,0.948747,Low
2,2026-08-20,Audiology,Audiology Assessment,1.333275,2,2,0,96.0,1.388828,Low
3,2026-08-20,CARDIOLOGY,Cardiology Consultation,0.264110,1,1,0,96.0,0.275114,Low
4,2026-08-20,CASUALTY,Emergency Consultation,4.029339,5,5,0,432.0,0.932717,Low

In [38]:
wks = pd.read_csv('weekly_capacity_simulation.csv')

In [39]:
wk.columns

Index(['week', 'QueuedTo', 'lgbm_prediction', 'prophet_prediction',
       'ensemble_prediction'],
      dtype='object')

In [40]:
weekly = pd.read_csv('weekly_capacity_simulation.csv')

In [41]:
weekly.head()

,week,department,service,is_24_7,operating_start,operating_end,service_time_mins,staff_available,rooms_available,forecast_demand,simulated_arrivals,weekly_capacity,capacity_surplus,patients_remaining,utilization_pct,congestion_status
0,2026-08-18,ADMISSION,Admission Processing,True,00:00,24:00,15.0,6,6,267.836913,268,4032.0,3764.163087,0,6.642781,Low
1,2026-08-18,Audiology,Audiology Assessment,False,08:00,16:00,30.0,6,6,12.401408,12,672.0,659.598592,0,1.845448,Low
2,2026-08-18,CARDIOLOGY,Cardiology Consultation,False,08:00,16:00,30.0,6,6,1.036948,1,672.0,670.963052,0,0.154308,Low
3,2026-08-18,CASUALTY,Emergency Consultation,True,00:00,24:00,20.0,6,6,38.344906,38,3024.0,2985.655094,0,1.268019,Low
4,2026-08-18,CHRONIC CARE CLINIC (DM/HTN/TB/CCC),Chronic Care Consultation,False,08:00,16:00,20.0,6,6,234.617064,235,1008.0,773.382936,0,23.275502,Low

In [66]:
weekly = weekly.rename(columns={
    "forecast_demand": "demand", 
})

In [73]:
weekly.columns

Index(['week', 'department', 'service', 'is_24_7', 'operating_start',
       'operating_end', 'service_time_mins', 'staff_available',
       'rooms_available', 'demand', 'simulated_arrivals', 'weekly_capacity',
       'capacity_surplus', 'patients_remaining', 'utilization_pct',
       'congestion_status'],
      dtype='object')

In [67]:
weekly.head()

,week,department,service,is_24_7,operating_start,operating_end,service_time_mins,staff_available,rooms_available,demand,simulated_arrivals,weekly_capacity,capacity_surplus,patients_remaining,utilization_pct,congestion_status
0,2026-08-18,ADMISSION,Admission Processing,True,00:00,24:00,15.0,6,6,267.836913,268,4032.0,3764.163087,0,6.642781,Low
1,2026-08-18,Audiology,Audiology Assessment,False,08:00,16:00,30.0,6,6,12.401408,12,672.0,659.598592,0,1.845448,Low
2,2026-08-18,CARDIOLOGY,Cardiology Consultation,False,08:00,16:00,30.0,6,6,1.036948,1,672.0,670.963052,0,0.154308,Low
3,2026-08-18,CASUALTY,Emergency Consultation,True,00:00,24:00,20.0,6,6,38.344906,38,3024.0,2985.655094,0,1.268019,Low
4,2026-08-18,CHRONIC CARE CLINIC (DM/HTN/TB/CCC),Chronic Care Consultation,False,08:00,16:00,20.0,6,6,234.617064,235,1008.0,773.382936,0,23.275502,Low

## Standardization

In [86]:
# ============================================================
# AFYAFLOW — UNIFIED DATA STANDARDIZATION
# ============================================================
# Purpose:
#   1. Load the 6 forecast/simulation source files
#   2. Standardize their column names and data types
#   3. Create a common schema
#   4. Combine Hourly + Daily + Weekly data
#   5. Validate the resulting dataset
#   6. Save afya_flow_unified.csv
#
# Run this entire cell in Jupyter.
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# 1. SET PROJECT DIRECTORY
# ============================================================

BASE_DIR = Path.cwd()

print("Project directory:")
print(BASE_DIR)

# ============================================================
# 2. SOURCE FILES
# ============================================================

FILES = {
    "hourly_forecast": BASE_DIR / "hourly_future_forecast.csv",
    "daily_forecast": BASE_DIR / "daily_7day_forecast.csv",
    "weekly_forecast": BASE_DIR / "future_weekly_ensemble.csv",

    "hourly_simulation": BASE_DIR / "hourly_capacity_simulation.csv",
    "daily_simulation": BASE_DIR / "daily_capacity_simulation.csv",
    "weekly_simulation": BASE_DIR / "weekly_capacity_simulation.csv",
}

# Check that all files exist
print("\nChecking source files...")

missing_files = []

for name, path in FILES.items():
    if path.exists():
        print(f"✓ {name}: {path.name}")
    else:
        print(f"✗ MISSING: {path.name}")
        missing_files.append(path.name)

if missing_files:
    raise FileNotFoundError(
        "\nThe following required files were not found:\n"
        + "\n".join(missing_files)
    )

# ============================================================
# 3. ROBUST CSV LOADER
# ============================================================
# Some of the AfyaFlow files may have been exported with
# the entire row wrapped in quotes. This loader handles both
# normal CSVs and that format.
# ============================================================

def load_afyaflow_csv(path):
    """
    Load an AfyaFlow CSV robustly.

    First attempts normal pandas CSV parsing.
    If the result appears malformed, falls back to manual
    parsing of rows wrapped in quotation marks.
    """

    path = Path(path)

    # First attempt: normal CSV
    try:
        df = pd.read_csv(path)

        # If pandas produced a sensible number of columns,
        # accept the result.
        if len(df.columns) > 1:
            df.columns = (
                df.columns
                .astype(str)
                .str.strip()
                .str.strip('"')
            )
            return df

    except Exception:
        pass

    # --------------------------------------------------------
    # Fallback loader
    # --------------------------------------------------------

    rows = []

    with open(path, "r", encoding="utf-8-sig") as f:

        for line in f:

            line = line.strip()

            if not line:
                continue

            # Remove outer quotation marks
            if line.startswith('"') and line.endswith('"'):
                line = line[1:-1]

            # Split comma-separated values
            rows.append(line.split(","))

    if not rows:
        raise ValueError(f"File is empty: {path}")

    header = [
        str(x).strip().strip('"')
        for x in rows[0]
    ]

    data = rows[1:]

    df = pd.DataFrame(data, columns=header)

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.strip('"')
    )

    return df


# ============================================================
# 4. LOAD ALL SIX FILES
# ============================================================

print("\nLoading source files...")

hourly_forecast = load_afyaflow_csv(FILES["hourly_forecast"])
daily_forecast = load_afyaflow_csv(FILES["daily_forecast"])
weekly_forecast = load_afyaflow_csv(FILES["weekly_forecast"])

hourly_simulation = load_afyaflow_csv(FILES["hourly_simulation"])
daily_simulation = load_afyaflow_csv(FILES["daily_simulation"])
weekly_simulation = load_afyaflow_csv(FILES["weekly_simulation"])

print("✓ All six files loaded successfully.")


# ============================================================
# 5. DISPLAY ORIGINAL COLUMNS
# ============================================================

print("\n" + "=" * 70)
print("ORIGINAL SOURCE COLUMNS")
print("=" * 70)

sources = {
    "Hourly Forecast": hourly_forecast,
    "Daily Forecast": daily_forecast,
    "Weekly Forecast": weekly_forecast,
    "Hourly Simulation": hourly_simulation,
    "Daily Simulation": daily_simulation,
    "Weekly Simulation": weekly_simulation,
}

for name, df in sources.items():

    print(f"\n{name}")
    print(f"Shape: {df.shape}")
    print("Columns:")
    print(list(df.columns))


# ============================================================
# 6. CLEAN COLUMN NAMES
# ============================================================

def clean_columns(df):
    df = df.copy()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.strip('"')
        .str.replace(" ", "_")
    )

    return df


hourly_forecast = clean_columns(hourly_forecast)
daily_forecast = clean_columns(daily_forecast)
weekly_forecast = clean_columns(weekly_forecast)

hourly_simulation = clean_columns(hourly_simulation)
daily_simulation = clean_columns(daily_simulation)
weekly_simulation = clean_columns(weekly_simulation)


# ============================================================
# 7. HELPER FUNCTION FOR COLUMN RENAMING
# ============================================================

def rename_if_exists(df, mapping):

    df = df.copy()

    actual_mapping = {}

    for old, new in mapping.items():

        if old in df.columns:
            actual_mapping[old] = new

    df = df.rename(columns=actual_mapping)

    return df


# ============================================================
# 8. STANDARDIZE FORECAST DATASETS
# ============================================================

# ------------------------------------------------------------
# HOURLY FORECAST
# ------------------------------------------------------------

hourly_forecast = rename_if_exists(
    hourly_forecast,
    {
        "date": "period",
        "Date": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",
    }
)

# If the hourly forecast contains a separate hour column,
# combine date + hour into period where appropriate.

if "period" in hourly_forecast.columns:

    # If period already contains time, keep it.
    period_as_string = hourly_forecast["period"].astype(str)

    if "hour" in hourly_forecast.columns:

        hour_as_string = hourly_forecast["hour"].astype(str)

        # Determine whether period already has a time component.
        has_time = period_as_string.str.contains(
            r"\d{1,2}:\d{2}",
            regex=True,
            na=False
        )

        combined = period_as_string.copy()

        combined.loc[~has_time] = (
            period_as_string.loc[~has_time]
            + " "
            + hour_as_string.loc[~has_time]
        )

        hourly_forecast["period"] = combined


# ------------------------------------------------------------
# DAILY FORECAST
# ------------------------------------------------------------

daily_forecast = rename_if_exists(
    daily_forecast,
    {
        "date": "period",
        "Date": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",
    }
)


# ------------------------------------------------------------
# WEEKLY FORECAST
# ------------------------------------------------------------

weekly_forecast = rename_if_exists(
    weekly_forecast,
    {
        "week": "period",
        "Week": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",
    }
)


# ============================================================
# 9. STANDARDIZE SIMULATION DATASETS
# ============================================================

# ------------------------------------------------------------
# HOURLY SIMULATION
# ------------------------------------------------------------

hourly_simulation = rename_if_exists(
    hourly_simulation,
    {
        "date": "period",
        "Date": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",

        "patients_arrivals": "simulated_arrivals",
        "patient_arrivals": "simulated_arrivals",
        "arrivals": "simulated_arrivals",

        "hourly_capacity": "capacity",

        "capacity_utilization_pct": "utilization_pct",
    }
)


# ------------------------------------------------------------
# DAILY SIMULATION
# ------------------------------------------------------------

daily_simulation = rename_if_exists(
    daily_simulation,
    {
        "date": "period",
        "Date": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "demand_forecast": "forecast_demand",
        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",

        "patients_arrivals": "simulated_arrivals",
        "patient_arrivals": "simulated_arrivals",
        "arrivals": "simulated_arrivals",

        "daily_capacity": "capacity",

        "capacity_utilization_pct": "utilization_pct",
    }
)


# ------------------------------------------------------------
# WEEKLY SIMULATION
# ------------------------------------------------------------

weekly_simulation = rename_if_exists(
    weekly_simulation,
    {
        "week": "period",
        "Week": "period",

        "QueuedTo": "department",
        "queuedto": "department",
        "Queued_To": "department",

        "demand_forecast": "forecast_demand",
        "prediction": "forecast_demand",
        "predicted_demand": "forecast_demand",
        "demand": "forecast_demand",

        "patients_arrivals": "simulated_arrivals",
        "patient_arrivals": "simulated_arrivals",
        "arrivals": "simulated_arrivals",

        "weekly_capacity": "capacity",

        "capacity_utilization_pct": "utilization_pct",
    }
)


# ============================================================
# 10. CHECK REQUIRED IDENTIFIER COLUMNS
# ============================================================

def check_required_columns(df, name):

    required = ["period", "department"]

    missing = [
        col for col in required
        if col not in df.columns
    ]

    if missing:

        raise KeyError(
            f"{name} is missing required columns: {missing}\n"
            f"Available columns: {list(df.columns)}"
        )


check_required_columns(hourly_forecast, "Hourly Forecast")
check_required_columns(daily_forecast, "Daily Forecast")
check_required_columns(weekly_forecast, "Weekly Forecast")

check_required_columns(hourly_simulation, "Hourly Simulation")
check_required_columns(daily_simulation, "Daily Simulation")
check_required_columns(weekly_simulation, "Weekly Simulation")


# ============================================================
# 11. CONVERT FORECAST DEMAND TO NUMERIC
# ============================================================

for df in [
    hourly_forecast,
    daily_forecast,
    weekly_forecast,
    hourly_simulation,
    daily_simulation,
    weekly_simulation,
]:

    if "forecast_demand" in df.columns:

        df["forecast_demand"] = pd.to_numeric(
            df["forecast_demand"],
            errors="coerce"
        )


# ============================================================
# 12. CONVERT SIMULATION NUMERIC COLUMNS
# ============================================================

NUMERIC_COLUMNS = [
    "forecast_demand",
    "simulated_arrivals",
    "patients_served",
    "patients_remaining",
    "maximum_queue",
    "average_wait_minutes",
    "capacity",
    "utilization_pct",
]

for df in [
    hourly_simulation,
    daily_simulation,
    weekly_simulation,
]:

    for col in NUMERIC_COLUMNS:

        if col in df.columns:

            df[col] = pd.to_numeric(
                df[col],
                errors="coerce"
            )


# ============================================================
# 13. STANDARDIZE PERIOD
# ============================================================

# Hourly
hourly_forecast["period"] = pd.to_datetime(
    hourly_forecast["period"],
    errors="coerce"
)

hourly_simulation["period"] = pd.to_datetime(
    hourly_simulation["period"],
    errors="coerce"
)

# Daily
daily_forecast["period"] = pd.to_datetime(
    daily_forecast["period"],
    errors="coerce"
)

daily_simulation["period"] = pd.to_datetime(
    daily_simulation["period"],
    errors="coerce"
)

# Weekly
# Keep the original weekly representation where possible.
weekly_forecast["period"] = (
    weekly_forecast["period"]
    .astype(str)
    .str.strip()
)

weekly_simulation["period"] = (
    weekly_simulation["period"]
    .astype(str)
    .str.strip()
)


# ============================================================
# 14. CREATE FORECAST-ONLY STANDARDIZED DATA
# ============================================================

FORECAST_COLUMNS = [
    "period",
    "department",
    "forecast_demand",
]

hourly_forecast_std = hourly_forecast.reindex(
    columns=FORECAST_COLUMNS
).copy()

daily_forecast_std = daily_forecast.reindex(
    columns=FORECAST_COLUMNS
).copy()

weekly_forecast_std = weekly_forecast.reindex(
    columns=FORECAST_COLUMNS
).copy()


# ============================================================
# 15. STANDARDIZE SIMULATION DATA
# ============================================================

CANONICAL_COLUMNS = [
    "period",
    "department",
    "service",
    "is_24_7",
    "operating",
    "forecast_demand",
    "simulated_arrivals",
    "patients_served",
    "patients_remaining",
    "maximum_queue",
    "average_wait_minutes",
    "capacity",
    "utilization_pct",
    "congestion_status",
]


def standardize_simulation(
    simulation_df,
    forecast_df,
    forecast_level
):

    df = simulation_df.copy()

    # --------------------------------------------------------
    # Make sure service exists
    # --------------------------------------------------------

    if "service" not in df.columns:
        df["service"] = np.nan

    # --------------------------------------------------------
    # If simulation doesn't contain forecast demand,
    # obtain it from the corresponding forecast dataset.
    # --------------------------------------------------------

    if (
        "forecast_demand" not in df.columns
        or df["forecast_demand"].isna().all()
    ):

        forecast_lookup = forecast_df[
            ["period", "department", "forecast_demand"]
        ].copy()

        forecast_lookup = forecast_lookup.drop_duplicates(
            subset=["period", "department"]
        )

        df = df.drop(
            columns=["forecast_demand"],
            errors="ignore"
        )

        df = df.merge(
            forecast_lookup,
            on=["period", "department"],
            how="left"
        )

    # --------------------------------------------------------
    # Ensure every canonical column exists
    # --------------------------------------------------------

    for col in CANONICAL_COLUMNS:

        if col not in df.columns:
            df[col] = np.nan

    # --------------------------------------------------------
    # Add forecast level
    # --------------------------------------------------------

    df["forecast_level"] = forecast_level

    # --------------------------------------------------------
    # Reorder columns
    # --------------------------------------------------------

    final_columns = [
        "forecast_level"
    ] + CANONICAL_COLUMNS

    df = df.reindex(
        columns=final_columns
    )

    return df


# ============================================================
# 16. CREATE STANDARDIZED SIMULATION TABLES
# ============================================================

hourly_std = standardize_simulation(
    hourly_simulation,
    hourly_forecast_std,
    "Hourly"
)

daily_std = standardize_simulation(
    daily_simulation,
    daily_forecast_std,
    "Daily"
)

weekly_std = standardize_simulation(
    weekly_simulation,
    weekly_forecast_std,
    "Weekly"
)


# ============================================================
# 17. CLEAN BOOLEAN COLUMNS
# ============================================================

def clean_boolean(series):

    if series.dtype == bool:
        return series

    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .map({
            "true": True,
            "false": False,
            "1": True,
            "0": False,
            "yes": True,
            "no": False
        })
    )


for df in [
    hourly_std,
    daily_std,
    weekly_std,
]:

    if "is_24_7" in df.columns:

        df["is_24_7"] = clean_boolean(
            df["is_24_7"]
        )


# ============================================================
# 18. CREATE OPERATING FLAG FOR HOURLY DATA
# ============================================================
# If the source simulation already has "operating", preserve it.
# Otherwise, derive it from is_24_7 and operating hours if those
# columns are available.
# ============================================================

if "operating" in hourly_std.columns:

    # Convert existing operating values if they exist
    if hourly_std["operating"].notna().any():

        hourly_std["operating"] = clean_boolean(
            hourly_std["operating"]
        )


# ============================================================
# 19. COMBINE THE THREE LEVELS
# ============================================================

afya_flow_unified = pd.concat(
    [
        hourly_std,
        daily_std,
        weekly_std
    ],
    ignore_index=True
)


# ============================================================
# 20. CREATE HUMAN-READABLE PERIOD LABEL
# ============================================================

afya_flow_unified["period_label"] = (
    afya_flow_unified["period"]
    .astype(str)
)

# Put period_label immediately after period
column_order = [
    "forecast_level",
    "period",
    "period_label",
    "department",
    "service",
    "is_24_7",
    "operating",
    "forecast_demand",
    "simulated_arrivals",
    "patients_served",
    "patients_remaining",
    "maximum_queue",
    "average_wait_minutes",
    "capacity",
    "utilization_pct",
    "congestion_status",
]

afya_flow_unified = afya_flow_unified.reindex(
    columns=column_order
)


# ============================================================
# 21. SORT THE DATA
# ============================================================

afya_flow_unified = afya_flow_unified.sort_values(
    by=[
        "forecast_level",
        "period",
        "department"
    ],
    na_position="last"
).reset_index(drop=True)


# ============================================================
# 22. REMOVE EXACT DUPLICATES
# ============================================================

duplicate_count = afya_flow_unified.duplicated().sum()

if duplicate_count > 0:

    print(
        f"\nRemoving {duplicate_count} exact duplicate rows."
    )

    afya_flow_unified = (
        afya_flow_unified
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ============================================================
# 23. SAVE UNIFIED DATASET
# ============================================================

OUTPUT_PATH = BASE_DIR / "afya_flow_unified.csv"

afya_flow_unified.to_csv(
    OUTPUT_PATH,
    index=False
)

print("\n" + "=" * 70)
print("UNIFIED DATASET CREATED")
print("=" * 70)

print(f"\nSaved to:")
print(OUTPUT_PATH)

print(f"\nShape: {afya_flow_unified.shape}")


# ============================================================
# 24. VALIDATION — ROW COUNTS
# ============================================================

print("\n" + "=" * 70)
print("ROWS BY FORECAST LEVEL")
print("=" * 70)

print(
    afya_flow_unified["forecast_level"]
    .value_counts()
)


# ============================================================
# 25. VALIDATION — DEPARTMENT COUNTS
# ============================================================

print("\n" + "=" * 70)
print("DEPARTMENTS BY FORECAST LEVEL")
print("=" * 70)

department_counts = (
    afya_flow_unified
    .groupby("forecast_level")["department"]
    .nunique()
)

print(department_counts)


# ============================================================
# 26. VALIDATION — DUPLICATES
# ============================================================

print("\n" + "=" * 70)
print("DUPLICATE CHECK")
print("=" * 70)

duplicate_keys = afya_flow_unified.duplicated(
    subset=[
        "forecast_level",
        "period",
        "department"
    ]
).sum()

print(
    "Duplicate level-period-department rows:",
    duplicate_keys
)


# ============================================================
# 27. VALIDATION — MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

missing_values = (
    afya_flow_unified
    .isna()
    .sum()
)

print(missing_values)


# ============================================================
# 28. VALIDATION — MISSING REQUIRED VALUES
# ============================================================

print("\n" + "=" * 70)
print("REQUIRED FIELD CHECK")
print("=" * 70)

required_columns = [
    "forecast_level",
    "period",
    "department",
    "forecast_demand",
]

for col in required_columns:

    missing = afya_flow_unified[col].isna().sum()

    print(
        f"{col}: {missing} missing"
    )


# ============================================================
# 29. VALIDATION — DEMAND VALUES
# ============================================================

print("\n" + "=" * 70)
print("DEMAND VALIDATION")
print("=" * 70)

negative_demand = (
    afya_flow_unified["forecast_demand"] < 0
).sum()

print(
    "Negative forecast demand:",
    negative_demand
)


# ============================================================
# 30. VALIDATION — CAPACITY
# ============================================================
# IMPORTANT:
#
# Hourly departments that are CLOSED can legitimately have
# capacity = 0.
#
# Therefore we only flag zero/negative hourly capacity when
# the department is operating.
#
# For Daily and Weekly data, capacity should normally be
# positive when demand exists.
# ============================================================

print("\n" + "=" * 70)
print("CAPACITY VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# Hourly
# ------------------------------------------------------------

hourly_check = afya_flow_unified[
    afya_flow_unified["forecast_level"] == "Hourly"
].copy()

if "operating" in hourly_check.columns:

    hourly_operating = hourly_check[
        hourly_check["operating"] == True
    ]

    bad_hourly_capacity = hourly_operating[
        (hourly_operating["forecast_demand"] > 0)
        &
        (
            hourly_operating["capacity"].isna()
            |
            (hourly_operating["capacity"] <= 0)
        )
    ]

else:

    bad_hourly_capacity = pd.DataFrame()


print(
    "Hourly operating periods with demand > 0 "
    "but zero/missing capacity:",
    len(bad_hourly_capacity)
)


# ------------------------------------------------------------
# Daily
# ------------------------------------------------------------

daily_check = afya_flow_unified[
    afya_flow_unified["forecast_level"] == "Daily"
].copy()

bad_daily_capacity = daily_check[
    (daily_check["forecast_demand"] > 0)
    &
    (
        daily_check["capacity"].isna()
        |
        (daily_check["capacity"] <= 0)
    )
]

print(
    "Daily periods with demand > 0 "
    "but zero/missing capacity:",
    len(bad_daily_capacity)
)


# ------------------------------------------------------------
# Weekly
# ------------------------------------------------------------

weekly_check = afya_flow_unified[
    afya_flow_unified["forecast_level"] == "Weekly"
].copy()

bad_weekly_capacity = weekly_check[
    (weekly_check["forecast_demand"] > 0)
    &
    (
        weekly_check["capacity"].isna()
        |
        (weekly_check["capacity"] <= 0)
    )
]

print(
    "Weekly periods with demand > 0 "
    "but zero/missing capacity:",
    len(bad_weekly_capacity)
)


# ============================================================
# 31. CHECK FOR MISSING WEEKLY DEPARTMENTS
# ============================================================

print("\n" + "=" * 70)
print("WEEKLY DEPARTMENT COVERAGE")
print("=" * 70)

daily_departments = set(
    daily_std["department"].dropna().unique()
)

weekly_departments = set(
    weekly_std["department"].dropna().unique()
)

missing_from_weekly = sorted(
    daily_departments - weekly_departments
)

print(
    "Departments in Daily but missing from Weekly:",
    len(missing_from_weekly)
)

if missing_from_weekly:

    print("\nMissing weekly departments:")

    for department in missing_from_weekly:
        print(" -", department)


# ============================================================
# 32. CONGESTION SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("CONGESTION STATUS")
print("=" * 70)

print(
    afya_flow_unified[
        "congestion_status"
    ]
    .value_counts(dropna=False)
)


# ============================================================
# 33. SHOW SAMPLE DATA
# ============================================================

print("\n" + "=" * 70)
print("FIRST 15 ROWS")
print("=" * 70)

display(
    afya_flow_unified.head(15)
)


# ============================================================
# 34. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("AFYAFLOW STANDARDIZATION COMPLETE")
print("=" * 70)

print(
    f"""
Unified dataset:
    {OUTPUT_PATH}

Rows:
    {len(afya_flow_unified):,}

Columns:
    {len(afya_flow_unified.columns)}

Hourly rows:
    {(afya_flow_unified["forecast_level"] == "Hourly").sum():,}

Daily rows:
    {(afya_flow_unified["forecast_level"] == "Daily").sum():,}

Weekly rows:
    {(afya_flow_unified["forecast_level"] == "Weekly").sum():,}

Duplicate keys:
    {duplicate_keys}

Negative demand values:
    {negative_demand}
"""
)

Project directory:
C:\Users\juan\DTS labs\Grad proj\simmulation

Checking source files...
✓ hourly_forecast: hourly_future_forecast.csv
✓ daily_forecast: daily_7day_forecast.csv
✓ weekly_forecast: future_weekly_ensemble.csv
✓ hourly_simulation: hourly_capacity_simulation.csv
✓ daily_simulation: daily_capacity_simulation.csv
✓ weekly_simulation: weekly_capacity_simulation.csv

Loading source files...
✓ All six files loaded successfully.

======================================================================
ORIGINAL SOURCE COLUMNS
======================================================================

Hourly Forecast
Shape: (6888, 4)
Columns:
['date', 'hour', 'department', 'demand']

Daily Forecast
Shape: (287, 3)
Columns:
['date', 'department', 'demand']

Weekly Forecast
Shape: (132, 3)
Columns:
['week', 'department', 'demand']

Hourly Simulation
Shape: (6888, 15)
Columns:
['date', 'hour', 'department', 'service', 'is_24_7', 'operating', 'forecast_demand', 'simulated_arrivals', 'patients_served', 'patients_remaining', 'maximum_queue', 'average_wait_minutes', 'capacity', 'utilization_pct', 'congestion_status']

Daily Simulation
Shape: (287, 10)
Columns:
['date', 'department', 'service', 'demand_forecast', 'patients_arrivals', 'patients_served', 'patients_remaining', 'daily_capacity', 'capacity_utilization_pct', 'congestion_status']

Weekly Simulation
Shape: (132, 16)
Columns:
['week', 'department', 'service', 'is_24_7', 'operating_start', 'operating_end', 'service_time_mins', 'staff_available', 'rooms_available', 'forecast_demand', 'simulated_arrivals', 'weekly_capacity', 'capacity_surplus', 'patients_remaining', 'utilization_pct', 'congestion_status']

======================================================================
UNIFIED DATASET CREATED
======================================================================

Saved to:
C:\Users\juan\DTS labs\Grad proj\simmulation\afya_flow_unified.csv

Shape: (7307, 16)

======================================================================
ROWS BY FORECAST LEVEL
======================================================================
forecast_level
Hourly    6888
Daily      287
Weekly     132
Name: count, dtype: int64

======================================================================
DEPARTMENTS BY FORECAST LEVEL
======================================================================
forecast_level
Daily     41
Hourly    41
Weekly    33
Name: department, dtype: int64

======================================================================
DUPLICATE CHECK
======================================================================
Duplicate level-period-department rows: 0

======================================================================
MISSING VALUES
======================================================================
forecast_level            0
period                    0
period_label              0
department                0
service                   0
is_24_7                 287
operating               419
forecast_demand           0
simulated_arrivals        0
patients_served         132
patients_remaining        0
maximum_queue           419
average_wait_minutes    419
capacity                  0
utilization_pct           0
congestion_status         0
dtype: int64

======================================================================
REQUIRED FIELD CHECK
======================================================================
forecast_level: 0 missing
period: 0 missing
department: 0 missing
forecast_demand: 0 missing

======================================================================
DEMAND VALIDATION
======================================================================
Negative forecast demand: 0

======================================================================
CAPACITY VALIDATION
======================================================================
Hourly operating periods with demand > 0 but zero/missing capacity: 0
Daily periods with demand > 0 but zero/missing capacity: 0
Weekly periods with demand > 0 but zero/missing capacity: 0

======================================================================
WEEKLY DEPARTMENT COVERAGE
======================================================================
Departments in Daily but missing from Weekly: 8

Missing weekly departments:
 - ANAESTHESIA
 - HTS
 - MEB PHYSIOTHERAPY
 - MENTAL HEALTH
 - PAEDS
 - PATHOLOGY
 - PEDIATRIC NEUROLOGY
 - RESPIRATORY CENTER

======================================================================
CONGESTION STATUS
======================================================================
congestion_status
Low           4302
High          2992
Overloaded       8
Critical         4
Moderate         1
Name: count, dtype: int64

======================================================================
FIRST 15 ROWS
======================================================================

,forecast_level,period,period_label,department,service,is_24_7,operating,forecast_demand,simulated_arrivals,patients_served,patients_remaining,maximum_queue,average_wait_minutes,capacity,utilization_pct,congestion_status
0,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,ADMISSION,Admission Processing,NaN,NaN,50.315600,51,51.0,0,NaN,NaN,576.0,8.735347,Low
1,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,ANAESTHESIA,Anaesthesia Service,NaN,NaN,0.910797,1,1.0,0,NaN,NaN,96.0,0.948747,Low
2,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,Audiology,Audiology Assessment,NaN,NaN,1.333275,2,2.0,0,NaN,NaN,96.0,1.388828,Low
3,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,CARDIOLOGY,Cardiology Consultation,NaN,NaN,0.264110,1,1.0,0,NaN,NaN,96.0,0.275114,Low
4,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,CASUALTY,Emergency Consultation,NaN,NaN,4.029339,5,5.0,0,NaN,NaN,432.0,0.932717,Low
5,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,CHRONIC CARE CLINIC (DM/HTN/TB/CCC),Chronic Care Consultation,NaN,NaN,49.895053,50,50.0,0,NaN,NaN,144.0,34.649342,Low
6,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,DAYCASE,Day Surgery,NaN,NaN,7.508815,8,8.0,0,NaN,NaN,48.0,15.643365,Low
7,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,DENTAL,Dental Consultation,NaN,NaN,15.644139,16,16.0,0,NaN,NaN,96.0,16.295979,Low
8,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,DIABETIC CLINIC,Diabetic Clinic Consultation,NaN,NaN,0.040761,1,1.0,0,NaN,NaN,144.0,0.028306,Low
9,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,EYE CLINIC,Ophthalmology Consultation,NaN,NaN,17.006146,18,18.0,0,NaN,NaN,96.0,17.714736,Low
10,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,FAMILY CLINIC,Family Clinic Consultation,NaN,NaN,0.385524,1,1.0,0,NaN,NaN,144.0,0.267725,Low
11,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,FAMILY MEDICINE,Family Medicine Consultation,NaN,NaN,0.119317,1,1.0,0,NaN,NaN,144.0,0.082859,Low
12,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,GENERAL OPD,General Consultation,NaN,NaN,123.092936,124,124.0,0,NaN,NaN,288.0,42.740603,Low
13,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,Gen Surg OPD,Surgical Consultation,NaN,NaN,6.347255,7,7.0,0,NaN,NaN,144.0,4.407816,Low
14,Daily,2026-08-20 00:00:00,2026-08-20 00:00:00,Gynae OPD,Gynaecology Consultation,NaN,NaN,0.058628,1,1.0,0,NaN,NaN,96.0,0.061071,Low

======================================================================
AFYAFLOW STANDARDIZATION COMPLETE
======================================================================

Unified dataset:
    C:\Users\juan\DTS labs\Grad proj\simmulation\afya_flow_unified.csv

Rows:
    7,307

Columns:
    16

Hourly rows:
    6,888

Daily rows:
    287

Weekly rows:
    132

Duplicate keys:
    0

Negative demand values:
    0

In [84]:
from pathlib import Path

print("Jupyter working directory:")
print(Path.cwd())

print("\nCSV files available under the current directory:")

for f in Path(".").rglob("*.csv"):
    print(f)

Jupyter working directory:
C:\Users\juan\DTS labs\Grad proj\simmulation

CSV files available under the current directory:
AfyaFlow_hospital_weekly_forecast.csv
afya_flow_7day_simulation.csv
afya_flow_dashboard_data.csv
afya_flow_department_summary.csv
afya_flow_unified.csv
daily_7day_forecast.csv
daily_capacity_simulation.csv
daily_forecast.csv
daily_future_forecast.csv
daily_future_forecast2.csv
future_weekly_ensemble-Copy1.csv
future_weekly_ensemble.csv
hourly_capacity_simulation.csv
hourly_forecast.csv
hourly_future_forecast.csv
opd_clean.csv
Opd_data.csv
weekly_capacity_simulation.csv
weekly_forecast.csv
.ipynb_checkpoints\daily_7day_forecast-checkpoint.csv
.ipynb_checkpoints\future_weekly_ensemble-checkpoint.csv
.ipynb_checkpoints\hourly_future_forecast-checkpoint.csv
.ipynb_checkpoints\weekly_capacity_simulation-checkpoint.csv
.ipynb_checkpoints\weekly_forecast-checkpoint.csv

## reload

In [89]:
hr.to_csv(
    "hourly_future_forecast.csv",
    index=False,
    encoding="utf-8"
)

dy.to_csv(
    "daily_7day_forecast.csv",
    index=False,
    encoding="utf-8"
) 

wk.to_csv(
    "future_weekly_ensemble.csv",
    index=False,
    encoding="utf-8"
)

dys.to_csv(
    "daily_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

hrs.to_csv(
    "hourly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

weekly.to_csv(
    "weekly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

In [91]:
import zipfile
from pathlib import Path

output_dir = Path("afyaFlow_exports")
output_dir.mkdir(exist_ok=True)

# Export the six DataFrames as real CSV files
hr.to_csv(
    "hourly_future_forecast.csv",
    index=False,
    encoding="utf-8"
)

dy.to_csv(
    "daily_7day_forecast.csv",
    index=False,
    encoding="utf-8"
) 

wk.to_csv(
    "future_weekly_ensemble.csv",
    index=False,
    encoding="utf-8"
)

dys.to_csv(
    "daily_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

hrs.to_csv(
    "hourly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

weekly.to_csv(
    "weekly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)


# Create ZIP
zip_path = Path("afyaFlow_exports.zip")

with zipfile.ZipFile(
    zip_path,
    "w",
    zipfile.ZIP_DEFLATED
) as zip_file:

    for csv_file in output_dir.glob("*.csv"):
        zip_file.write(
            csv_file,
            arcname=csv_file.name
        )

print(f"Created: {zip_path}")

Created: afyaFlow_exports.zip

In [93]:
print("daily:", type(hr))
print("hourly:", type(dy))
print("weekly:", type(weekly))

daily: <class 'pandas.core.frame.DataFrame'>
hourly: <class 'pandas.core.frame.DataFrame'>
weekly: <class 'pandas.core.frame.DataFrame'>

In [94]:
print([x for x in globals() if "simulation" in x.lower()])

['hourly_simulation', 'daily_simulation', 'weekly_simulation', 'standardize_simulation']

In [96]:
import zipfile
from pathlib import Path

# ---------------------------------------------------------
# Create export folder
# ---------------------------------------------------------

export_dir = Path("afyaFlow_exports")
export_dir.mkdir(exist_ok=True)


# ---------------------------------------------------------
# Export the six DataFrames as genuine CSV files
# ---------------------------------------------------------

dy.to_csv(
    export_dir / "daily_7day_forecast.csv",
    index=False,
    encoding="utf-8"
)

hr.to_csv(
    export_dir / "hourly_future_forecast.csv",
    index=False,
    encoding="utf-8"
)

wk.to_csv(
    export_dir / "future_weekly_ensemble.csv",
    index=False,
    encoding="utf-8"
)

dys.to_csv(
    export_dir / "daily_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

hrs.to_csv(
    export_dir / "hourly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)

weekly.to_csv(
    export_dir / "weekly_capacity_simulation.csv",
    index=False,
    encoding="utf-8"
)


# ---------------------------------------------------------
# Create ZIP
# ---------------------------------------------------------

zip_path = Path("afyaFlow_exports.zip")

with zipfile.ZipFile(
    zip_path,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as z:

    for csv_file in export_dir.glob("*.csv"):
        z.write(
            csv_file,
            arcname=csv_file.name
        )


# ---------------------------------------------------------
# VERIFY ZIP CONTENTS
# ---------------------------------------------------------

print("ZIP CREATED:")
print(zip_path.resolve())

print("\nFILES INSIDE ZIP:")

with zipfile.ZipFile(zip_path, "r") as z:
    for name in z.namelist():
        print("  ✓", name)

print("\nNUMBER OF FILES:", len(z.namelist()))

ZIP CREATED:
C:\Users\juan\DTS labs\Grad proj\simmulation\afyaFlow_exports.zip

FILES INSIDE ZIP:
  ✓ daily_7day_forecast.csv
  ✓ daily_capacity_simulation.csv
  ✓ future_weekly_ensemble.csv
  ✓ hourly_capacity_simulation.csv
  ✓ hourly_future_forecast.csv
  ✓ weekly_capacity_simulation.csv

NUMBER OF FILES: 6